trigger:
- none

pool:
  name: Default


variables:
  solution: 'MessageServer/MessageServer.csproj'
  buildConfiguration: 'Release'

jobs:
- job: Build
  steps:
  - script: dotnet --version
    displayName: 'Verify .NET Version'

  - script: dotnet restore $(solution)
    displayName: 'Restore NuGet packages'

  - script: dotnet build $(solution) --configuration $(buildConfiguration)
    displayName: 'Build the solution'
  
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Manics Dev Subscription(69bc8425-0a8a-4584-bcfd-f98effdeb5e5)'
      appType: 'webApp'
      WebAppName: 'messageserver'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

- job: Publish
  displayName: 'Publish Artifact'
  dependsOn: Build
  steps:
  - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    artifact: drop